apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: deepseek-pipeline
  annotations:
    scenarios.ai.sap.com/description: "DeepSeek reasoning model"
    scenarios.ai.sap.com/name: "DeepSeek Reasoner"
    executables.ai.sap.com/description: "Runs DeepSeek inference on prompts"
    executables.ai.sap.com/name: "DeepSeek Inference"
  labels:
    scenarios.ai.sap.com/id: "deepseek"
    ai.sap.com/version: "1.0"
spec:
  imagePullSecrets:
    - name: your-docker-secret # if your Docker image is private; else remove
  entrypoint: deepseek-entry
  templates:
    - name: deepseek-entry
      steps:
        - - name: deepseek-step
            template: deepseek-container

    - name: deepseek-container
      container:
        image: madanmathvan/deepseek:latest
        command: ["/bin/sh", "-c"]
        args:
          - "uvicorn app:app --host 0.0.0.0 --port 9001"
        env:
          - name: MODEL_PATH
            value: "/app/model/DeepSeek-R1-Distill-Qwen-1.5B-Q4_1.gguf"
