apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: deepseek-serving-001
  annotations:
    scenarios.ai.sap.com/description: "DeepSeek reasoning model for online inference"
    scenarios.ai.sap.com/name: "DeepSeek Reasoner"
    executables.ai.sap.com/description: "Runs DeepSeek inference on prompts"
    executables.ai.sap.com/name: "deepseek-serving"
    artifacts.ai.sap.com/deepseekmodel.kind: "model"
  labels:
    scenarios.ai.sap.com/id: "deepseek-reasoner"
    ai.sap.com/version: "1.0"
spec:
  inputs:
    artifacts:
      - name: deepseekmodel
        type: model
        uri: "https://github.com/Madan-Madhavan/evora-deepseek-tiny/releases/download/model-artifact/DeepSeek-R1-Distill-Qwen-1.5B-Q4_1.gguf"
    parameters:
      - name: port
        type: string
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: starter
    spec: |
      predictor:
        minReplicas: 1
        maxReplicas: 3
        containers:
          - name: kserve-container
            image: "madanmathavan/deepseek:latest"
            ports:
              - containerPort: 9001
                protocol: TCP
            command: ["/bin/sh", "-c"]
            args:
              - >
                set -e && echo "Starting DeepSeek Serving..." && python /app/app.py
            env:
              - name: MODEL_PATH
                value: "https://github.com/Madan-Madhavan/evora-deepseek-tiny/releases/download/model-artifact/DeepSeek-R1-Distill-Qwen-1.5B-Q4_1.gguf"
              - name: PORT
                value: "{{inputs.parameters.port}}"
