apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: deepseek-tiny
spec:
  template:
    apiVersion: ai.sap.com/v1alpha1
    kind: Serving
    metadata:
      name: deepseek-tiny
    spec:
      replicas: 1
      predictor:
        containers:
          - name: deepseek
            image: madanmathvan/deepseek:latest
            ports:
              - containerPort: 9001
            resources:
              limits:
                memory: "8Gi"
                cpu: "4"
